export enum MechEquipmentTag {
  Energy = 'Energy',
  Ballistic = 'Ballistic',
  DirectFire = 'Direct-Fire',
  Pulse = 'Pulse',
  AntiInfantry = 'Anti-Infantry',
  AreaEffect = 'Area Effect',
  Cluster = 'Cluster',
  HeatCausing = 'Heat Causing',
  MissileWeapon = 'Missile Weapon',
  RapidFiring = 'Rapid Firing',
  OneShot = 'One-Shot',
  VaraibleDamage = 'Variable Damage',
  Flak = 'Flak',
  SwitchableAmmoSupply = 'Switchable Ammo Supply',
  Electronics = 'Electronics',
  CounterElectronics = 'Counter-Electronics',
  TargetingSystem = 'Targeting System',
}
