export enum Hardpoint {
  Empty = 'Empty',
  Sensors = 'Sensors',
  Shoulder = 'Shoulder',
  UpperArmActuator = 'UpperArmActuator',
  LowerArmActuator = 'LowerArmActuator',
  Hip = 'Hip',
  UpperLegActuator = 'UpperLegActuator',
  LowerLegActuator = 'LowerLegActuator',
  FootActuator = 'FootActuator',
  Cockpit = 'Cockpit',
  LifeSupport = 'LifeSupport',
  Engine = 'Engine',
  Gyro = 'Gyro',
  Energy = 'Energy',
  Ballistic = 'Ballistic',
  Missile = 'Missile',
  Omni = 'Omni',
  MissileAmmo = 'MissileAmmo',
  BallisticAmmo = 'BallisticAmmo',
  HeatSink = 'HeatSink',
  JumpJet = 'JumpJet',
  EndoSteel = 'EndoSteel',
  FerroFibrous = 'FerroFibrous',
}
