export enum MechEquipmentType {
  Ballistic = 'Ballistic',
  BallisticAmmo = 'BallisticAmmo',
  Autocannon = 'Autocannon',
  Gauss_Rifle = 'Gauss Rifle',
  Machine_Gun = 'Machine Gun',
  AMS = 'AMS',

  Energy = 'Energy',
  EnergyAmmo = 'EnergyAmmo',
  Flamer = 'Flamer',
  Laser = 'Laser',
  Pulse_Laser = 'Pulse Laser',
  Plasma = 'Plasma',
  PPC = 'PPC',
  Laser_AMS = 'Laser AMS',
  TAG = 'TAG',

  Missile = 'Missile',
  MissileAmmo = 'MissileAmmo',
  LRM = 'LRM',
  MRM = 'MRM',
  SRM = 'SRM',
  MML = 'MML',
  ATM = 'ATM',
  Rocket_Launcher = 'Rocket Launcher',
  NARC_Launcher = 'NARC Launcher',

  Electronics = 'Electronics',
  Heatsink = 'Heatsink',
  Jump_Jet = 'Jump Jet',
  Internal_Structure = 'Internal Structure',
  Armor = 'Armor',
  ECM_Suite = 'ECM Suite',
  Active_Probe = 'Active Probe',
  MASC = 'MASC',
  CASE = 'CASE',
  C3_Computer = 'C3 Computer',
  Targeting_Computer = 'Targeting Computer',
  Artemis_IV = 'Artemis IV',
}
